### ISSUE TITLE
[BUG] The Recent Stats shows the word "Latest" twice.

### ISSUE THREAD

**Issue by Pinak-Datta** [Pinak-Datta/PypiMeter#1]
**Describe the bug encountered**
After fetching the statistics, under the Recent Stats section, instead of *"Last Day"*, or *"Last Week"* it shows *"Last Last Day"*, and *"Last Last Week"*.

**To Reproduce**
Steps to reproduce the behaviour:
1. Type in any package name and hit Submit.
2. The redundancy can be found under the "Recent Stats section"

**Screenshots**

<img width="289" alt="image" src="https://github.com/Pinak-Datta/PypiMeter/assets/87294070/3983a176-ad60-4912-ab16-96167ad670da">

**Comment by Angelles** [comment]
@Pinak-Datta I think the issue is resolved, as I do not see this error:
<img width="559" alt="image" src="https://github.com/Pinak-Datta/PypiMeter/assets/10748229/9c93e943-5594-439d-9109-3005a8218254">
Try clearing your cache.

**Comment by Pinak-Datta** [comment]
Yup!
Apparently, the latest commit changes are only reflected after restarting the app on streamlit cloud!
Thanks!
